"""add financial_natures

Revision ID: a916c7a53579
Revises: e8645eefc6a6
Create Date: 2026-03-13 09:52:07.880130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a916c7a53579'
down_revision = 'e8645eefc6a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_natures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('financial_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financial_nature_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'financial_natures', ['financial_nature_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('financial_nature_id')

    op.drop_table('financial_natures')
    # ### end Alembic commands ###
